version: '3'
services:
  app:
    build:
      context: ./app
    command: npm run watch
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
      - "35792:35792"
    links:
      - redis
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
  redis:
    image: redis:latest
    ports:
      - "6379"
  